(() => {
  const $ = (sel, root = document) => root.querySelector(sel);
  let config = JSON.parse($('#defaultPricingConfig').textContent);
  let protectedCosts = new Map();
  let project = null;

  const els = {
    projectName: $('#projectName'), clientName: $('#clientName'), targetMargin: $('#targetMargin'),
    metrics: $('#projectMetrics'), phases: $('#phasesContainer'), phaseBody: $('#phaseSummaryBody'),
    phaseFoot: $('#phaseSummaryFoot'), saveStatus: $('#saveStatus'), projectFile: $('#projectFile'),
    phaseDefinitionBody: $('#phaseDefinitionBody'), phaseDefinitionEmpty: $('#phaseDefinitionEmpty'),
    projectResourceBody: $('#projectResourceBody'), projectResourceEmpty: $('#projectResourceEmpty'),
    unlockOverlay: $('#unlockOverlay'), unlockPassword: $('#unlockPassword'), unlockBtn: $('#unlockBtn'),
    unlockMessage: $('#unlockMessage'), reportView: $('#reportView')
  };

  function createBlankProject() {
    return { version: 3, name: '', client: '', targetMargin: config.marginTargets?.target ?? 50, resourceIds: [], phases: [newPhase('Discovery')] };
  }
  function newPhase(name = 'New Phase') { const phase = { id: cryptoId(), name, startDate: '', endDate: '', assignments: [] }; if (project) syncPhaseAssignments(phase); return phase; }
  function assignmentFor(resourceId) { const resource = resourceById(resourceId), role = roleById(resource?.roleId); return { id: cryptoId(), resourceId, hoursPerWeek: 0, billingRate: role?.defaultRate ?? 0 }; }
  function cryptoId() { if (window.crypto?.randomUUID) return window.crypto.randomUUID(); return 'id-' + Math.random().toString(36).slice(2) + Date.now().toString(36); }
  function roleById(id) { return config.roles.find(r => String(r.id) === String(id)); }
  function resourceById(id) { return config.resources.find(r => String(r.id) === String(id)); }
  function syncPhaseAssignments(phase) { phase.assignments = phase.assignments || []; const byResource = new Map(phase.assignments.map(a => [String(a.resourceId), a])); phase.assignments = (project?.resourceIds || []).map(resourceId => byResource.get(String(resourceId)) || assignmentFor(resourceId)); }
  function syncAllAssignments() { project.phases.forEach(syncPhaseAssignments); }

  function businessDaysInclusive(start, end) {
    if (!start || !end) return 0; const s = new Date(start + 'T12:00:00'), e = new Date(end + 'T12:00:00');
    if (Number.isNaN(s.getTime()) || Number.isNaN(e.getTime()) || e < s) return 0;
    let count = 0, d = new Date(s); while (d <= e) { const day = d.getDay(); if (day !== 0 && day !== 6) count++; d.setDate(d.getDate() + 1); } return count;
  }
  function phaseWeeks(phase) { return businessDaysInclusive(phase.startDate, phase.endDate) / 5; }
  function assignmentCalc(phase, a) {
    const weeks = phaseWeeks(phase), hours = weeks * Number(a.hoursPerWeek || 0), revenue = hours * Number(a.billingRate || 0);
    const costRate = protectedCosts.get(String(a.resourceId)); const cost = Number.isFinite(costRate) ? hours * costRate : 0;
    const margin = revenue - cost, marginPct = revenue > 0 ? margin / revenue * 100 : null;
    return { weeks, hours, revenue, cost, margin, marginPct };
  }
  function phaseCalc(phase) {
    const totals = phase.assignments.map(a => assignmentCalc(phase,a)).reduce((acc,r) => ({hours:acc.hours+r.hours,revenue:acc.revenue+r.revenue,cost:acc.cost+r.cost,margin:acc.margin+r.margin}), {hours:0,revenue:0,cost:0,margin:0});
    return {...totals,weeks:phaseWeeks(phase),marginPct:totals.revenue>0?totals.margin/totals.revenue*100:null};
  }
  function projectCalc() {
    const totals = project.phases.map(phaseCalc).reduce((acc,r) => ({hours:acc.hours+r.hours,revenue:acc.revenue+r.revenue,cost:acc.cost+r.cost,margin:acc.margin+r.margin}), {hours:0,revenue:0,cost:0,margin:0});
    return {...totals,marginPct:totals.revenue>0?totals.margin/totals.revenue*100:null,avgBillRate:totals.hours>0?totals.revenue/totals.hours:0};
  }

  function currency(n, decimals=0) { return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:decimals,maximumFractionDigits:decimals}).format(Number(n||0)); }
  function number(n,digits=1) { return new Intl.NumberFormat('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(Number(n||0)); }
  function pct(n) { return n == null ? '—' : `${number(n,1)}%`; }
  function formatDate(v) { if (!v) return 'Date not set'; const d=new Date(v+'T12:00:00'); return d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}); }
  function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
  function escapeAttr(v){return escapeHtml(v);}
  function marginClass(v){ if(v==null)return 'pending'; const target=Number(project.targetMargin||0); if(v>=target)return 'good'; if(v>=Math.max(0,target-10))return 'warn'; return 'bad'; }

  function render(){ syncAllAssignments(); els.projectName.value=project.name||''; els.clientName.value=project.client||''; els.targetMargin.value=Number(project.targetMargin??config.marginTargets?.target??50); renderPhaseDefinitions(); renderProjectResources(); renderPhaseAllocations(); renderMetrics(); renderPhaseSummary(); }
  function renderPhaseDefinitions(){ els.phaseDefinitionBody.innerHTML=''; els.phaseDefinitionEmpty.hidden=project.phases.length>0; project.phases.forEach((phase,index)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td><input class="phase-name" type="text" value="${escapeAttr(phase.name)}" placeholder="Phase name" /></td><td><input class="phase-start" type="date" value="${escapeAttr(phase.startDate)}" /></td><td><input class="phase-end" type="date" value="${escapeAttr(phase.endDate)}" /></td><td><strong class="definition-weeks">${number(phaseWeeks(phase),2)}</strong></td><td class="no-print"><button class="icon-btn remove-definition-phase" title="Remove phase">×</button></td>`; $('.phase-name',tr).addEventListener('input',e=>{phase.name=e.target.value;changed();renderPhaseAllocations();renderPhaseSummary();}); $('.phase-start',tr).addEventListener('change',e=>{phase.startDate=e.target.value;changed();render();}); $('.phase-end',tr).addEventListener('change',e=>{phase.endDate=e.target.value;changed();render();}); $('.remove-definition-phase',tr).addEventListener('click',()=>{project.phases.splice(index,1);changed();render();}); els.phaseDefinitionBody.appendChild(tr); }); }
  function resourceTypeRank(resource){const t=String(resource?.resourceType||'').trim().toLowerCase();if(t==='employee')return 0;if(t==='contractor')return 1;return 2;}
  function compareResources(a,b){const typeDiff=resourceTypeRank(a)-resourceTypeRank(b);if(typeDiff!==0)return typeDiff;return String(a?.name||'').localeCompare(String(b?.name||''),undefined,{sensitivity:'base'});}
  function sortResourceIds(ids){return [...ids].sort((a,b)=>compareResources(resourceById(a),resourceById(b)));}
  function availableResources(){return config.resources.filter(r=>!project.resourceIds.map(String).includes(String(r.id))).sort(compareResources);}
  function renderProjectResources(){ els.projectResourceBody.innerHTML=''; els.projectResourceEmpty.hidden=project.resourceIds.length>0; sortResourceIds(project.resourceIds).forEach((resourceId)=>{const resource=resourceById(resourceId);if(!resource)return;const role=roleById(resource.roleId),tr=document.createElement('tr');tr.innerHTML=`<td><strong>${escapeHtml(resource.name)}</strong><small class="resource-type">${escapeHtml(resource.resourceType||'')}</small></td><td>${escapeHtml(role?.name||'—')}</td><td>${role?`${currency(role.minimumRate)}–${currency(role.maximumRate)}`:'—'}</td><td>${role?currency(role.defaultRate):'—'}</td><td class="no-print"><button class="icon-btn remove-project-resource" title="Remove resource from project">×</button></td>`;$('.remove-project-resource',tr).addEventListener('click',()=>{project.resourceIds=project.resourceIds.filter(id=>String(id)!==String(resourceId));syncAllAssignments();changed();render();});els.projectResourceBody.appendChild(tr);}); }
  function addProjectResource(){const available=availableResources();if(!available.length){alert('All available resources are already on the project.');return;}const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<div class="modal-card"><div class="section-heading"><div><h2>Add Project Resource</h2><p>Select a resource to add to every phase.</p></div></div><label><span>Resource</span><select id="resourcePicker">${available.map(r=>{const role=roleById(r.roleId);return `<option value="${escapeAttr(r.id)}">${escapeHtml(r.name)}${role?' — '+escapeHtml(role.name):''}</option>`;}).join('')}</select></label><div class="modal-actions"><button class="btn secondary" id="cancelResource">Cancel</button><button class="btn primary" id="confirmResource">Add Resource</button></div></div>`;document.body.appendChild(overlay);$('#cancelResource',overlay).addEventListener('click',()=>overlay.remove());$('#confirmResource',overlay).addEventListener('click',()=>{const id=$('#resourcePicker',overlay).value;project.resourceIds.push(id);project.resourceIds=sortResourceIds(project.resourceIds);syncAllAssignments();changed();overlay.remove();render();});}
  function renderPhaseAllocations(){els.phases.innerHTML='';if(!project.phases.length){els.phases.innerHTML='<div class="empty-state">Define at least one project phase first.</div>';return;}project.phases.forEach(phase=>{const node=$('#phaseAllocationTemplate').content.cloneNode(true),card=$('.phase-card',node);card.dataset.phaseId=phase.id;$('.allocation-phase-name',card).textContent=phase.name||'Unnamed Phase';$('.allocation-phase-dates',card).textContent=`${formatDate(phase.startDate)} – ${formatDate(phase.endDate)}`;$('.phase-weeks',card).textContent=number(phaseWeeks(phase),2);const tbody=$('.resource-body',card);if(!project.resourceIds.length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="8" class="allocation-empty">Add resources to the project team above. They will automatically appear here.</td>';tbody.appendChild(tr);}else{phase.assignments.forEach(a=>{const rowNode=$('#resourceAllocationTemplate').content.cloneNode(true);populateAllocationRow($('.resource-row',rowNode),phase,a);tbody.appendChild(rowNode);});}const pc=phaseCalc(phase);$('.phase-total',card).textContent=`${number(pc.hours)} hrs · ${currency(pc.revenue)} revenue · ${pct(pc.marginPct)} margin`;const invalidDates=phase.startDate&&phase.endDate&&new Date(phase.endDate)<new Date(phase.startDate);$('.phase-warning',card).textContent=invalidDates?'End date must be on or after start date.':'';els.phases.appendChild(node);});}
  function populateAllocationRow(row,phase,a){const resource=resourceById(a.resourceId),role=roleById(resource?.roleId);$('.resource-name',row).textContent=resource?.name||'Unknown resource';$('.role-name',row).textContent=role?.name||'—';const hoursInput=$('.hours-week',row),rateInput=$('.billing-rate',row),slider=$('.rate-slider',row);hoursInput.value=Number(a.hoursPerWeek||0);rateInput.value=Number(a.billingRate||0);if(role){slider.min=role.minimumRate;slider.max=role.maximumRate;slider.step=1;$('.rate-min',row).textContent=currency(role.minimumRate);$('.rate-max',row).textContent=currency(role.maximumRate);}else{slider.disabled=true;$('.rate-min',row).textContent='—';$('.rate-max',row).textContent='—';}updateAllocationRow(row,phase,a);hoursInput.addEventListener('input',e=>{a.hoursPerWeek=Number(e.target.value||0);changed();updateAllocationRow(row,phase,a);recalcOnly();});rateInput.addEventListener('input',e=>{a.billingRate=Number(e.target.value||0);changed();updateAllocationRow(row,phase,a);recalcOnly();});slider.addEventListener('input',e=>{a.billingRate=Number(e.target.value);rateInput.value=a.billingRate;changed();updateAllocationRow(row,phase,a);recalcOnly();});}
  function updateAllocationRow(row,phase,a){const resource=resourceById(a.resourceId),role=roleById(resource?.roleId),calc=assignmentCalc(phase,a);$('.row-hours',row).textContent=number(calc.hours);$('.row-revenue',row).textContent=currency(calc.revenue);const pill=$('.margin-pill',row);pill.textContent=pct(calc.marginPct);pill.className=`margin-pill ${marginClass(calc.marginPct)}`;const msg=$('.rate-message',row),sliderStatus=$('.slider-status',row),slider=$('.rate-slider',row);msg.className='rate-message';sliderStatus.className='slider-status';if(!role){msg.textContent='';sliderStatus.textContent='';return;}const rate=Number(a.billingRate||0),clamped=Math.min(role.maximumRate,Math.max(role.minimumRate,rate));slider.value=clamped;slider.classList.toggle('out-of-range',rate<role.minimumRate||rate>role.maximumRate);if(rate<role.minimumRate){msg.textContent=`Below minimum by ${currency(role.minimumRate-rate)}`;msg.classList.add('low');sliderStatus.textContent=`↓ ${currency(rate)} is below range`;sliderStatus.classList.add('low');}else if(rate>role.maximumRate){msg.textContent=`Above maximum by ${currency(rate-role.maximumRate)}`;msg.classList.add('high');sliderStatus.textContent=`↑ ${currency(rate)} is above range`;sliderStatus.classList.add('high');}else{msg.textContent='Within range';msg.classList.add('ok');sliderStatus.textContent=`${currency(rate)} selected`;sliderStatus.classList.add('ok');}}
  function renderMetrics(){const t=projectCalc();els.metrics.innerHTML=[metric('Project Phases',String(project.phases.length),'Defined project phases'),metric('Project Team',String(project.resourceIds.length),'Resources on project'),metric('Project Hours',number(t.hours),'Planned resource hours'),metric('Client Price',currency(t.revenue),'Total project revenue'),metric('Gross Margin',pct(t.marginPct),`${currency(t.margin)} gross margin`,marginClass(t.marginPct)),metric('Avg. Bill Rate',currency(t.avgBillRate),'Weighted by planned hours')].join('');}
  function metric(label,value,sub,cls=''){return `<div class="metric-card ${cls}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong><small>${escapeHtml(sub)}</small></div>`;}
  function renderPhaseSummary(){els.phaseBody.innerHTML='';project.phases.forEach(phase=>{const c=phaseCalc(phase),tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(phase.name||'Unnamed Phase')}</td><td>${number(c.weeks,2)}</td><td>${number(c.hours)}</td><td>${currency(c.revenue)}</td><td>${currency(c.margin)}</td><td><span class="margin-pill ${marginClass(c.marginPct)}">${pct(c.marginPct)}</span></td>`;els.phaseBody.appendChild(tr);});const t=projectCalc();els.phaseFoot.innerHTML=`<tr><td>Total</td><td>—</td><td>${number(t.hours)}</td><td>${currency(t.revenue)}</td><td>${currency(t.margin)}</td><td>${pct(t.marginPct)}</td></tr>`;}
  function recalcOnly(){renderMetrics();renderPhaseSummary();project.phases.forEach(phase=>{const card=$(`.phase-card[data-phase-id="${CSS.escape(phase.id)}"]`);if(!card)return;const pc=phaseCalc(phase);$('.phase-total',card).textContent=`${number(pc.hours)} hrs · ${currency(pc.revenue)} revenue · ${pct(pc.marginPct)} margin`;});}
  function changed(){els.saveStatus.textContent='Unsaved changes';}
  function normalizeProject(p){const phases=(p?.phases||p?.project?.phases||[]).map(ph=>({id:ph.id||cryptoId(),name:ph.name||'Phase',startDate:ph.startDate||'',endDate:ph.endDate||'',assignments:(ph.assignments||[]).map(a=>({id:a.id||cryptoId(),resourceId:String(a.resourceId||a.resource||''),hoursPerWeek:Number(a.hoursPerWeek||0),billingRate:Number(a.billingRate||0)}))}));let resourceIds=(p?.resourceIds||p?.project?.resourceIds||[]).map(String);if(!resourceIds.length){const found=new Set();phases.forEach(ph=>ph.assignments.forEach(a=>{if(a.resourceId)found.add(String(a.resourceId));}));resourceIds=[...found];}const valid=new Set(config.resources.map(r=>String(r.id)));resourceIds=sortResourceIds(resourceIds.filter(id=>valid.has(String(id))));return{version:3,name:p?.name||p?.project?.name||'',client:p?.client||p?.project?.client||'',targetMargin:Number(p?.targetMargin??p?.project?.targetMargin??config.marginTargets?.target??50),resourceIds,phases:phases.length?phases:[newPhase('Discovery')]};}
  async function readJsonFile(file){return JSON.parse(await file.text());}
  function downloadJson(obj,filename){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  function safeFileName(name){return(name||'Project').replace(/[^a-z0-9-_]+/gi,'_').replace(/^_+|_+$/g,'')||'Project';}

  function b64ToBytes(s){const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
  async function decryptResources(password){const p=window.PROTECTED_RESOURCE_DATA;if(!p)throw new Error('Protected resource data is missing.');if(!window.crypto?.subtle)throw new Error('This browser does not support the required encryption APIs. Use a current version of Microsoft Edge or Chrome.');const enc=new TextEncoder(),keyMaterial=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64ToBytes(p.salt),iterations:p.iterations,hash:'SHA-256'},keyMaterial,{name:'AES-GCM',length:256},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(p.iv)},key,b64ToBytes(p.ciphertext));return JSON.parse(new TextDecoder().decode(plain));}
  async function unlock(){const password=els.unlockPassword.value;if(!password){els.unlockMessage.textContent='Enter the pricing-data password.';return;}els.unlockBtn.disabled=true;els.unlockBtn.textContent='Unlocking…';els.unlockMessage.textContent='';try{const data=await decryptResources(password);if(!Array.isArray(data.resources))throw new Error('Invalid resource payload.');config.resources=data.resources.map(r=>({id:String(r.id),name:r.name,roleId:r.roleId,resourceType:r.resourceType||''})).sort(compareResources);protectedCosts=new Map(data.resources.map(r=>[String(r.id),Number(r.costRate)]));try{localStorage.removeItem('projectPricingTool.currentProject');}catch{}project=createBlankProject();els.unlockPassword.value='';els.unlockOverlay.classList.add('hidden');render();}catch(err){console.error(err);els.unlockMessage.textContent='Unable to unlock. Check the password and try again.';}finally{els.unlockBtn.disabled=false;els.unlockBtn.textContent='Unlock';}}

  function resourceSummaryRows(){return project.resourceIds.map(id=>{const r=resourceById(id),role=roleById(r?.roleId);let hours=0,revenue=0,margin=0;project.phases.forEach(ph=>{const a=ph.assignments.find(x=>String(x.resourceId)===String(id));if(a){const c=assignmentCalc(ph,a);hours+=c.hours;revenue+=c.revenue;margin+=c.margin;}});return{resource:r?.name||'Unknown',role:role?.name||'—',hours,revenue,margin,marginPct:revenue>0?margin/revenue*100:null};});}
  function renderReport(){const t=projectCalc(),generated=new Date().toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'});const phaseRows=project.phases.map(ph=>{const c=phaseCalc(ph);return`<tr><td>${escapeHtml(ph.name)}</td><td>${escapeHtml(formatDate(ph.startDate))}</td><td>${escapeHtml(formatDate(ph.endDate))}</td><td>${number(c.weeks,2)}</td><td>${number(c.hours)}</td><td>${currency(c.revenue)}</td><td>${currency(c.margin)}</td><td>${pct(c.marginPct)}</td></tr>`;}).join('');const resourceRows=resourceSummaryRows().map(r=>`<tr><td>${escapeHtml(r.resource)}</td><td>${escapeHtml(r.role)}</td><td>${number(r.hours)}</td><td>${currency(r.revenue)}</td><td>${currency(r.margin)}</td><td>${pct(r.marginPct)}</td></tr>`).join('');const detail=project.phases.map(ph=>`<div class="report-phase"><h3>${escapeHtml(ph.name||'Unnamed Phase')}</h3><div class="report-sub">${escapeHtml(formatDate(ph.startDate))} - ${escapeHtml(formatDate(ph.endDate))} · ${number(phaseWeeks(ph),2)} planning weeks</div><table><thead><tr><th>Resource</th><th>Role</th><th>Hours/Wk</th><th>Bill Rate</th><th>Total Hours</th><th>Revenue</th><th>Margin</th><th>Margin %</th></tr></thead><tbody>${ph.assignments.map(a=>{const r=resourceById(a.resourceId),role=roleById(r?.roleId),c=assignmentCalc(ph,a);return`<tr><td>${escapeHtml(r?.name||'Unknown')}</td><td>${escapeHtml(role?.name||'—')}</td><td>${number(a.hoursPerWeek)}</td><td>${currency(a.billingRate)}</td><td>${number(c.hours)}</td><td>${currency(c.revenue)}</td><td>${currency(c.margin)}</td><td>${pct(c.marginPct)}</td></tr>`;}).join('')}</tbody></table></div>`).join('');els.reportView.innerHTML=`<div class="report-header"><div><div class="report-kicker">THRIVENCE PROJECT PRICING</div><h1>${escapeHtml(project.name||'Untitled Project')}</h1><p>${escapeHtml(project.client||'Client not specified')}</p></div><div class="report-meta"><strong>Internal Pricing Report</strong><span>Generated ${escapeHtml(generated)}</span></div></div><div class="report-metrics"><div><span>Project Hours</span><strong>${number(t.hours)}</strong></div><div><span>Client Price</span><strong>${currency(t.revenue)}</strong></div><div><span>Gross Margin</span><strong>${currency(t.margin)}</strong></div><div><span>Margin %</span><strong>${pct(t.marginPct)}</strong></div><div><span>Avg. Bill Rate</span><strong>${currency(t.avgBillRate)}</strong></div><div><span>Target Margin</span><strong>${number(project.targetMargin,1)}%</strong></div></div><h2>Phase Summary</h2><table><thead><tr><th>Phase</th><th>Start</th><th>End</th><th>Weeks</th><th>Hours</th><th>Revenue</th><th>Margin</th><th>Margin %</th></tr></thead><tbody>${phaseRows}</tbody></table><h2>Resource Summary</h2><table><thead><tr><th>Resource</th><th>Role</th><th>Hours</th><th>Revenue</th><th>Margin</th><th>Margin %</th></tr></thead><tbody>${resourceRows}</tbody></table><h2>Detailed Phase Allocations</h2>${detail}<div class="report-footer">Confidential - Internal pricing information</div>`;}
  function exportReport(){renderReport();setTimeout(()=>window.print(),50);}

  $('#addPhaseBtn').addEventListener('click',()=>{project.phases.push(newPhase(`Phase ${project.phases.length+1}`));changed();render();});
  $('#addProjectResourceBtn').addEventListener('click',addProjectResource);
  els.projectName.addEventListener('input',e=>{project.name=e.target.value;changed();});els.clientName.addEventListener('input',e=>{project.client=e.target.value;changed();});els.targetMargin.addEventListener('input',e=>{project.targetMargin=Number(e.target.value||0);changed();recalcOnly();});
  $('#saveProjectBtn').addEventListener('click',()=>{downloadJson(project,`${safeFileName(project.client)}_${safeFileName(project.name)}_Pricing.json`);els.saveStatus.textContent='Project exported';});
  $('#loadProjectBtn').addEventListener('click',()=>els.projectFile.click());$('#printBtn').addEventListener('click',exportReport);
  els.projectFile.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{project=normalizeProject(await readJsonFile(file));changed();render();}catch(err){alert(`Could not open project file: ${err.message}`);}finally{e.target.value='';}});
  els.unlockBtn.addEventListener('click',unlock);els.unlockPassword.addEventListener('keydown',e=>{if(e.key==='Enter')unlock();});
  els.unlockPassword.focus();
})();
